name: Test

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - run: docker run -d --name seq -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:latest
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run lint
